import { FoodItem } from "./types";

export const COMMON_FOOD_ITEMS: FoodItem[] = [
  {
    name: "Grilled Chicken Breast",
    calories: 240,
    protein: 46,
    carbs: 0,
    fat: 4.5,
    fiber: 0,
    servingSize: "150g",
    description: "Lean high-protein chicken breast grilled with light seasoning.",
  },
  {
    name: "Cooked White Rice",
    calories: 205,
    protein: 4.2,
    carbs: 44.5,
    fat: 0.4,
    fiber: 0.6,
    servingSize: "1 cup (158g)",
    description: "Standard cooked long-grain white jasmine rice.",
  },
  {
    name: "Cooked Brown Rice",
    calories: 218,
    protein: 5.0,
    carbs: 45.8,
    fat: 1.6,
    fiber: 3.5,
    servingSize: "1 cup (195g)",
    description: "Whole grain brown rice, rich in dietary fiber and nutrients.",
  },
  {
    name: "Large Hass Avocado",
    calories: 240,
    protein: 3,
    carbs: 12,
    fat: 22,
    fiber: 10,
    servingSize: "1 medium avocado",
    description: "Creamy whole avocado containing heart-healthy monounsaturated fats.",
  },
  {
    name: "Hard-Boiled Egg",
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
    servingSize: "1 large (50g)",
    description: "Standard whole chicken egg boiled to high completion.",
  },
  {
    name: "Oatmeal (Rolled Oats with Water/Milk)",
    calories: 154,
    protein: 6.0,
    carbs: 28.0,
    fat: 3.0,
    fiber: 4.0,
    servingSize: "1 cooked cup",
    description: "Warm breakfast oats containing slow-digesting complex carbohydrates.",
  },
  {
    name: "Plain Greek Yogurt (0% Fat)",
    calories: 100,
    protein: 17.0,
    carbs: 6.0,
    fat: 0.4,
    fiber: 0,
    servingSize: "1 container (170g)",
    description: "Strained non-fat high protein active culture yogurt.",
  },
  {
    name: "Pan-Seared Salmon Fillet",
    calories: 242,
    protein: 25.0,
    carbs: 0,
    fat: 15.0,
    fiber: 0,
    servingSize: "120g",
    description: "Atlantic salmon containing essential omega-3 fatty acids.",
  },
  {
    name: "Whole Wheat Bread",
    calories: 140,
    protein: 7.0,
    carbs: 24.0,
    fat: 1.8,
    fiber: 3.8,
    servingSize: "2 slices",
    description: "Whole grain sliced bread with nutritional dietary fibers.",
  },
  {
    name: "Creamy Peanut Butter",
    calories: 188,
    protein: 8.0,
    carbs: 6.0,
    fat: 16.0,
    fiber: 1.9,
    servingSize: "2 tbsp (32g)",
    description: "Rich nut butter offering highly dense calories and healthy fats.",
  },
  {
    name: "Fresh Red Apple",
    calories: 95,
    protein: 0.5,
    carbs: 25.0,
    fat: 0.3,
    fiber: 4.4,
    servingSize: "1 medium apple",
    description: "Crisp and juicy sweet apple with beneficial fiber.",
  },
  {
    name: "Sweet Banana",
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.3,
    fiber: 3.1,
    servingSize: "1 medium fruit",
    description: "Perfect portable dynamic source of dietary potassium.",
  },
  {
    name: "Raw Almonds",
    calories: 164,
    protein: 6.0,
    carbs: 6.1,
    fat: 14.1,
    fiber: 3.5,
    servingSize: "1 oz (28g / ~23 nuts)",
    description: "Incredibly nutrient-dense unsalted almonds.",
  },
  {
    name: "Whey Protein Shake",
    calories: 140,
    protein: 25.0,
    carbs: 3.0,
    fat: 2.0,
    fiber: 1.0,
    servingSize: "1 scoop in water",
    description: "Fast-acting filtered protein supplement for recovery.",
  },
  {
    name: "Mixed Garden Salad",
    calories: 120,
    protein: 1.5,
    carbs: 6.0,
    fat: 10.0,
    fiber: 2.5,
    servingSize: "1 large bowl",
    description: "Crispy greens and cucumber dressed with simple olive oil dressing.",
  },
];
